<?php
/** op-unit-form:/testcase/action.phtml
 *
 * @created   2019-03-01
 * @version   1.0
 * @package   op-unit-form
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** Declare strict
 *
 */
declare(strict_types=1);

/** namespace
 *
 * @created    2019-03-01
 * @changed    2024-03-09  OP --> OP\UNIT\FORM;
 */
namespace OP\UNIT\FORM;

/* @var  $form  \OP\UNIT\Form */
$validate = $form->Validate();
$validate['isValidate'] = $form->isValidate();
$validate['token']      = $form->Token();
?>
<section class="breadcrumb-navigation">
[
	<?php foreach( ['text','password','textarea','select','radio','checkbox','multiple','agree'] as $key ): ?>
	<span><a href="<?= $key ?>"><?= $key ?></a></span>
	<?php endforeach; ?>
]
</section>
<section>
	<?php $form->Start() ?>
	<table id="op-unit-form">
		<?php foreach( $form->Config()['input'] as $input ): ?>
		<tr>
			<th><?php $form->Label($input['name']) ?></th>
			<td><?php $form->Input($input['name']) ?></td>
			<td><?php $form->Value($input['name']) ?></td>
			<td><?php $form->Error($input['name']) ?></td>
		</tr>
		<?php endforeach; ?>
	</table>
	<?php $form->Finish() ?>
</section>
<style>
#op-unit-form th,
#op-unit-form td {
	_border: 1px solid white;
	padding-right: 0.5rem;
}
</style>
<?php
//	...
D($validate);

//	...
$form->Debug();
